# Generated by Django 5.2.6 on 2025-10-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (EN)')),
                ('name_kk', models.CharField(blank=True, default='', max_length=100, verbose_name='Атауы (KK)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('description_kk', models.TextField(blank=True, default='', verbose_name='Сипаттама (KK)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('show_in_nav', models.BooleanField(default=True, help_text='Показывать в навбаре', verbose_name='Показывать в навбаре')),
                ('nav_position', models.PositiveIntegerField(default=0, help_text='Порядок в навбаре', verbose_name='Порядок в навбаре')),
                ('is_21plus', models.BooleanField(default=False, help_text='Скрывать до подтверждения 21+', verbose_name='Скрывать до подтверждения 21+')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['position', 'name_ru'],
                'indexes': [models.Index(fields=['position'], name='menuapp_cat_positio_eaa0d9_idx'), models.Index(fields=['nav_position'], name='menuapp_cat_nav_pos_afebe2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=150, verbose_name='Название (EN)')),
                ('name_kk', models.CharField(blank=True, default='', max_length=150, verbose_name='Атауы (KK)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('description_kk', models.TextField(blank=True, default='', verbose_name='Сипаттама (KK)')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Слаг')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото блюда')),
                ('passport_bg', models.ImageField(blank=True, null=True, upload_to='dishes/passports/', verbose_name='Фон-паспорт')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menuapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['category', 'position', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('kitchen', 'На кухне'), ('ready', 'Готово')], default='new', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.dish', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='menuapp.OrderItem', to='menuapp.dish', verbose_name='Позиции'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'dish'), name='uniq_order_dish'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='menuapp_ord_status_040b52_idx'),
        ),
    ]
