# Generated by Django 5.2.1 on 2025-11-04 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['nav_position', 'position', 'id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category', 'position', 'id'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='menuapp_cat_nav_pos_afebe2_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_21plus',
            field=models.BooleanField(default=False, verbose_name='Скрывать до подтверждения 21+'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nav_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в навбаре'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_nav',
            field=models.BooleanField(default=True, verbose_name='Показывать в навбаре'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Название (RU)'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_nav', 'nav_position'], name='menuapp_cat_show_in_7b57cf_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'position'], name='menuapp_dis_categor_992b29_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_available'], name='menuapp_dis_is_avai_b0a035_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['slug'], name='menuapp_dis_slug_ffb014_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='menuapp_ord_user_id_0cc222_idx'),
        ),
    ]
