# Generated by Django 5.2.6 on 2025-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_add_i18n_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(max_length=150, verbose_name='Название (RU)'),
        ),
    ]
