# Generated by Django 4.2.19 on 2025-10-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_alter_category_name_ru_alter_dish_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category', 'position', 'id'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_21plus',
            field=models.BooleanField(default=False, verbose_name='Скрывать до подтверждения 21+'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nav_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в навбаре'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_nav',
            field=models.BooleanField(default=True, verbose_name='Показывать в навбаре'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Название (RU)'),
        ),
    ]
