# Generated by Django 4.2.19 on 2025-10-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_alter_category_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['nav_position', 'position', 'id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='menuapp_cat_nav_pos_afebe2_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_nav', 'nav_position'], name='menuapp_cat_show_in_7b57cf_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'position'], name='menuapp_dis_categor_992b29_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_available'], name='menuapp_dis_is_avai_b0a035_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['slug'], name='menuapp_dis_slug_ffb014_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='menuapp_ord_user_id_0cc222_idx'),
        ),
    ]
